<?php require_once __DIR__.'/config/db.php'; $page_title='MediNova — Modern Pharmacy'; $featured=$pdo->query("SELECT p.*,c.name category_name,c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.stock>0 ORDER BY p.is_featured DESC,p.id DESC LIMIT 8")->fetchAll(); $cats=$pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll(); require __DIR__.'/includes/store_header.php'; ?>
<main>
<section class="hero"><div class="hero-grid"></div><div class="hero-copy reveal"><p class="eyebrow"><span></span> Modern pharmacy · human care</p><h1>HEALTH,<br><em>REIMAGINED.</em></h1><p class="hero-text">Medicines, wellness, skincare and everyday care — presented in a calmer pharmacy experience built around you.</p><div class="hero-ctas"><a class="btn btn-light" href="<?=BASE_URL?>shop.php">Explore pharmacy ↗</a><a class="text-link" href="<?=BASE_URL?>services.php">Our services →</a></div></div><div class="hero-art"><div class="hero-radial hero-radial-a"></div><div class="hero-radial hero-radial-b"></div><div class="orb orb-a"></div><div class="orb orb-b"></div><div class="capsule capsule-one"><span></span><b>MEDI</b></div><div class="capsule capsule-two"><span></span><b>CARE</b></div><div class="medicine-bottle"><i></i><strong>MEDI<br>NOVA</strong><small>PHARMACY</small></div><div class="floating-pill pill-a"></div><div class="floating-pill pill-b"></div><div class="floating-pill pill-c"></div><div class="ring ring-one"></div><div class="ring ring-two"></div><div class="floating-card card-top"><small>24/7</small><strong>CARE</strong></div><div class="floating-card card-bottom"><small>FAST</small><strong>DELIVERY</strong></div></div><div class="hero-badge"><span class="pulse-dot"></span> OPEN FOR YOUR HEALTH · 24/7 CARE</div><div class="hero-bottom"><span>MEDINOVA / 2026</span><div class="line"></div><span>SCROLL TO EXPLORE ↓</span></div></section>
<section class="ticker"><div class="ticker-track"><span>MEDICINES</span><b>✦</b><span>WELLNESS</span><b>✦</b><span>SKINCARE</span><b>✦</b><span>FIRST AID</span><b>✦</b><span>PERSONAL CARE</span><b>✦</b><span>MEDICINES</span><b>✦</b></div></section>
<section class="section intro"><div class="section-label">[ 01 / THE EXPERIENCE ]</div><div class="intro-content reveal"><p class="kicker">A PHARMACY BUILT DIFFERENTLY</p><h2>Everything you need.<br><span>One calmer place.</span></h2><p>Browse real pharmacy categories, order from your phone or desktop, create your own account, track orders and get support — without exposing the admin system to customers.</p><a class="btn btn-light" href="<?=BASE_URL?>categories.php">Browse categories ↗</a></div></section>
<section class="content-section"><div class="section-head reveal"><div><p class="kicker">SHOP BY CATEGORY</p><h2>Find your <span>care.</span></h2></div><a class="text-link" href="<?=BASE_URL?>categories.php">All categories →</a></div><div class="service-cards" style="margin-top:30px"><?php foreach($cats as $i=>$c): ?><a class="service-card" href="<?=BASE_URL?>shop.php?category=<?=e($c['slug'])?>" style="text-decoration:none;color:#fff"><span class="service-number">0<?=($i+1)?></span><h3><?=e($c['name'])?></h3><p style="color:#7f887f;line-height:1.7"><?=e($c['description']??'Quality products for everyday care.')?></p></a><?php endforeach; ?></div></section>
<section class="content-section" id="featured"><div class="section-head reveal"><div><p class="kicker">CURATED ESSENTIALS</p><h2>Shop the <span>edit.</span></h2></div><a class="text-link" href="<?=BASE_URL?>shop.php">View all products →</a></div><div class="shop-grid" style="margin-top:30px"><?php foreach($featured as $p): ?><article class="shop-card"><a href="<?=BASE_URL?>product.php?slug=<?=e($p['slug'])?>"><div class="art" style="--glow:rgba(217,255,84,.18)"><?php if(!empty($p['image'])): ?><img src="<?=BASE_URL?><?=e($p['image'])?>" alt="<?=e($p['name'])?>"><?php else: ?><div class="medicine-art"><i class="pill"></i><i class="pill p2"></i></div><?php endif; ?></div></a><div class="shop-info"><small><?=e($p['category_name']??'Pharmacy')?></small><h3><?=e($p['name'])?></h3><div class="shop-foot"><strong>Rs. <?=number_format((float)$p['price'])?></strong><button class="add-cart" data-id="<?=$p['id']?>">+</button></div></div></article><?php endforeach; ?></div></section>
<section class="feature section"><div class="feature-visual reveal"><div class="visual-grid"></div><div class="crosshair">+</div><div class="feature-orb"></div><div class="feature-label"><span>01</span><strong>CARE / IN MOTION</strong></div></div><div class="feature-copy reveal"><p class="kicker">MORE THAN A STORE</p><h2>A better way to <span>care.</span></h2><p>Separate customer and admin experiences, secure accounts, real stock management, order tracking and online payment infrastructure.</p><div class="service-list"><div><b>01</b><span>Real product images</span><small>Uploaded by admin</small></div><div><b>02</b><span>Secure customer accounts</span><small>Private customer area</small></div><div><b>03</b><span>Online payment ready</span><small>JazzCash gateway structure</small></div></div></div></section>
<section class="statement section"><p class="kicker">DESIGNED AROUND YOU</p><h2 class="reveal">Less friction.<br><span>More care.</span></h2><div class="statement-meta"><span>MEDINOVA / 2026</span><span>SECURE PHARMACY EXPERIENCE</span></div></section>
</main><?php require __DIR__.'/includes/store_footer.php'; ?>
